### ISSUE TITLE
使用AVfoundation添加水印，视频长度被缩短了

### ISSUE THREAD

**Issue by hj4859199** [DamonHu/VideoEditDemo#3]
我使用AVfoundation的方式添加水印，10s长度的视频添加完水印之后只有8s左右，最后的两s左右的视频丢失了，而且添加水印失败之后没有回调吗？

**Comment by DamonHu** [comment]
首先你看加水印代码里面，开始时间和结束时间都专门少了0.2，这个就是开始时间和结束时间的控制，至于代表的长度，不妨去百度下CMTime，为什么这么做，是为了防止一部分视频出现保存在相册，封面变成黑屏问题，当然你可以设置为0

```
CMTime startTime = CMTimeMakeWithSeconds(0.2, 600);
    CMTime endTime = CMTimeMakeWithSeconds(videoAsset.duration.value/videoAsset.duration.timescale-0.2, videoAsset.duration.timescale);
```

其次回调问题，保存的状态示例里面下面这一段就是说的生成状态啊

```
if (error) {
                    [SVProgressHUD showErrorWithStatus:[NSString stringWithFormat:@"%@",error]];
                }
                else{
                    [SVProgressHUD showSuccessWithStatus:@"视频已经保存到相册"];
                }
            }else {
                [SVProgressHUD showErrorWithStatus:NSLocalizedString(@"视频保存相册失败，请设置软件读取相册权限", nil)];
            }
```

如果你是说没有用block块专门做了个回调，那这个应该不能算问题吧

**Comment by hj4859199** [comment]
谢谢你的回答，实在不好意思，由于时间问题没有仔细的阅读源码，确实看到了你对视频的开始和结尾做了处理，这个问题解决了，还有一个问题是使用你的demo运行GPUImage方式添加水印，直接crash了，你可以试一下，我截图上传失败了

**Comment by DamonHu** [comment]
是替换了视频吗？还是直接运行的原demo里面的视频，不知道是权限问题还是视频缺少了东西，在手机上试了下没有复现。^_^
对于处理过程中的回调、代理之类写的很随意的情况是因为这个视频编辑之前想过封装成一个现成的库，但是后面考虑了下，一是太懒了，没有精力维护，二是直接写个demo有看到需要的部分直接移植就行了，所以就没有再考虑那么全面了
